name: 'CoreDeploy'
description: 'Uploads a package to CoreDeploy server'
inputs:
  appid:
    description: 'ID of the app in CoreDeploy'
    required: true
    default: ''
  version:
    description: 'version of the app'
    required: true
    default: ''
  artifact:
    description: 'Path to the artifact zip file'
    required: true
    default: ''
  url:
    description: 'Ingress server URL'
    required: true
    default: ''
  key:
    description: 'Ingress key'
    required: true
    default: ''
  token:
    description: 'GitHub token'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'