name: Test_Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create a dummy package
        run: | 
          mkdir ${{github.workspace}}/test
          dd if=/dev/zero of=${{github.workspace}}/test/artifact.zip  bs=5M  count=1

      - name: Core Deploy
        uses: itniels/CoreDeploy.Action@main
        with:
          appid: 21
          version: 1.1.${{github.run_id}}
          artifact: ${{github.workspace}}/test/artifact.zip
          message: ${{github.event.head_commit.message}}
          url: ${{secrets.COREDEPLOY_URL}}
          key: ${{secrets.COREDEPLOY_INGRESSKEY}}
